name: Formal Ledger Specs
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.nixos.org/
      - run: nix-build -A agdaLedger
      - run: nix-build -A ledger.executableSpec -j1 
      - run: nix-build -A ledger.docs -j1
      - run: nix-build -A midnight.executableSpec -j1
      - run: nix-build -A midnight.docs -j1
